# Generated by Django 5.0.6 on 2024-06-04 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=25)),
                ('ciudad', models.CharField(blank=True, max_length=25, null=True)),
                ('direccion_sucursal', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono_sucursal', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=25)),
                ('salario', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('encargado_departamento', models.CharField(blank=True, max_length=40, null=True)),
                ('nombre_departamento', models.CharField(max_length=25)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('RUT', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(blank=True, max_length=9, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('cargo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo')),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('RUT_contacto', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido1_contacto', models.CharField(max_length=20)),
                ('apellido2_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('relacion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('RUT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='CargaFamiliar',
            fields=[
                ('RUT_carga', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_carga', models.CharField(max_length=20)),
                ('apellido1_carga', models.CharField(max_length=20)),
                ('apellido2_carga', models.CharField(blank=True, max_length=20, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=15, null=True)),
                ('sexo', models.CharField(blank=True, max_length=9, null=True)),
                ('RUT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateField()),
                ('fecha_termino_contrato', models.DateField(blank=True, null=True)),
                ('RUT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
            options={
                'unique_together': {('RUT', 'fecha_contratacion')},
            },
        ),
    ]
